#True
print(9>7)
print(7<9)
print(True or False)
print(False or True)
print(True and True)
print(9>1)
print(5<9)
print(True or False)
print(False or True)
print(True and True)
#False
print(9<7)
print(7>9)
print(True and False)
print(False and True)
print(False or False)

print(9==7)
print(7==6)
print(True and False)
print(False and True)
print(False or False)
